/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gehan.hasilpertandingan1;

import java.awt.Color;

/**
 *
 * @author Ge
 */
public class StartScreen extends javax.swing.JFrame {

    public class ClubEPL {
        private String[] club;

        public String[] getClub() {
            return club;
        }

        public void setClub(String[] club) {
            this.club = club;
        }

        public static void main(String[] args) {

            String[] Club = {
                "Arsenal", "Chelsea", "Liverpool", "Manchester City", "Manchester United"
            };
            
        }
        
    }
 
    
    public StartScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbClub = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        rbEPL = new javax.swing.JRadioButton();
        rbUCL = new javax.swing.JRadioButton();
        rbUEL = new javax.swing.JRadioButton();
        rbFA = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        labelW = new javax.swing.JLabel();
        labelD = new javax.swing.JLabel();
        labelL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fixtures Sepakbola");
        setBounds(new java.awt.Rectangle(350, 150, 500, 0));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Hasil Pertandingan Sepakbola");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Pilih Club :");

        cbClub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Club-", "Arsenal", "Chelsea", "Liverpool", "Manchester City", "Manchester United" }));
        cbClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClubActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Pilih Kompetisi :");

        bg.add(rbEPL);
        rbEPL.setText("Premier League");
        rbEPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEPLActionPerformed(evt);
            }
        });

        bg.add(rbUCL);
        rbUCL.setText("UEFA Champions League");
        rbUCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbUCLActionPerformed(evt);
            }
        });

        bg.add(rbUEL);
        rbUEL.setText("UEFA Europa League");
        rbUEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbUELActionPerformed(evt);
            }
        });

        bg.add(rbFA);
        rbFA.setText("FA Cup");
        rbFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFAActionPerformed(evt);
            }
        });

        jButton1.setText("Cek Hasil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ta.setEditable(false);
        ta.setColumns(20);
        ta.setRows(5);
        ta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(ta);

        labelW.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        labelW.setForeground(new java.awt.Color(255, 255, 255));
        labelW.setText("W = Win (Menang)");

        labelD.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        labelD.setForeground(new java.awt.Color(255, 255, 255));
        labelD.setText("D = Draw (Seri)");

        labelL.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        labelL.setForeground(new java.awt.Color(255, 255, 255));
        labelL.setText("L = Lose (Kalah)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbUEL)
                                            .addComponent(rbUCL)
                                            .addComponent(rbFA)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(cbClub, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(rbEPL))))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelW, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelD)
                            .addComponent(labelL))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbEPL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbFA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbUCL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbUEL)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(labelW)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbUELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbUELActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbUELActionPerformed

    private void rbUCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbUCLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbUCLActionPerformed

    private void rbFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFAActionPerformed

    private void rbEPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEPLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEPLActionPerformed

    private void cbClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClubActionPerformed
        // TODO add your handling code here:
        String selectedClub = cbClub.getSelectedItem().toString();

        if (selectedClub.equals("-Pilih Club-")) {
            Error2 warning = new Error2();
            warning.setVisible(true);
            this.dispose();
        } else if (selectedClub.equals("Arsenal")) {
            rbEPL.setEnabled(true);
            rbFA.setEnabled(true);
            rbUEL.setEnabled(true);
            rbUCL.setEnabled(false);
        } else if (selectedClub.equals("Chelsea")) {
            rbEPL.setEnabled(true);
            rbFA.setEnabled(true);
            rbUEL.setEnabled(false);
            rbUCL.setEnabled(true);
        } else if (selectedClub.equals("Liverpool")) {
            rbEPL.setEnabled(true);
            rbFA.setEnabled(true);
            rbUEL.setEnabled(false);
            rbUCL.setEnabled(true);
        } else if (selectedClub.equals("Manchester City")) {
            rbEPL.setEnabled(true);
            rbFA.setEnabled(true);
            rbUEL.setEnabled(false);
            rbUCL.setEnabled(true);
        } else if (selectedClub.equals("Manchester United")) {
            rbEPL.setEnabled(true);
            rbFA.setEnabled(true);
            rbUEL.setEnabled(true);
            rbUCL.setEnabled(false);
        }

    }//GEN-LAST:event_cbClubActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String selectedClub = cbClub.getSelectedItem().toString();
        String result = "";

        switch (selectedClub) {
            case "-Pilih Club-" -> {
                Error2 warning = new Error2();
                warning.setVisible(true);
                this.dispose();
            }
            case "Arsenal" -> {
                if (rbEPL.isSelected()) {
                    result = ("""
                              Form 5 pertandingan Terakhir : W-W-L-L-W
                              
                              Finish Pada Posisi ke-2 Di Liga
                              
                              = Kualifikasi UEFA Champions League 2023/2024 =
                              
                              = Kualifikasi Community Shield Cup =
                            """);
                    labelW.setForeground(Color.black);
                    labelD.setForeground(Color.black);
                    labelL.setForeground(Color.black);   
                } else if (rbFA.isSelected()) {
                    result = ("""
                              Third Round : W
                              
                              Fourth Round : L
                              
                              = Gugur Pada Ronde Putaran ke-4  FA Cup =
                              """);
                    labelW.setForeground(Color.black);
                    labelD.setForeground(Color.black);
                    labelL.setForeground(Color.black);
                } else if (rbUEL.isSelected()) {
                    result = ("""
                             Group Stage : Lolos
                             Form : W-W-W-W-L-W
                              
                             Round of 16 : D-L
                             
                             = Gugur pada Round Of 16 UEFA Europa League =
                             """);
                    labelW.setForeground(Color.black);
                    labelD.setForeground(Color.black);
                    labelL.setForeground(Color.black);
                } else {
                    Error1 warning = new Error1();
                    warning.setVisible(true);
                    this.dispose();
                }
            }
            case "Chelsea" -> {
                if (rbEPL.isSelected()) {
                    result = ("""
                              Form 5 pertandingan Terakhir: W-D-L-L-D
                                                                       
                              Finish Pada Posisi ke-12 Di Liga
                              
                              = Tidak Dapat Mengikut Kompetisi Eropa =
                              """);
                    labelW.setForeground(Color.black);
                    labelD.setForeground(Color.black);
                    labelL.setForeground(Color.black);
                } else if (rbFA.isSelected()) {
                    result = ("""
                              Third Round : L
                              
                              = Gugur pada ronde putaran ke-3  FA Cup =
                              """);
                    labelW.setForeground(Color.black);
                    labelD.setForeground(Color.black);
                    labelL.setForeground(Color.black);
                } else if (rbUCL.isSelected()) {
                    result = ("""
                              Group Stage : Lolos
                              Form : L-D-W-W-W-W
                              
                              Round of 16 : L-W
                              (Menang Agregate)
                              
                              Quarter Final : L-L
                              
                              = Gugur pada Quarter Final UEFA Champions League =
                              """);
                    labelW.setForeground(Color.black);
                    labelD.setForeground(Color.black);
                    labelL.setForeground(Color.black);
                } else {
                    Error1 warning = new Error1();
                    warning.setVisible(true);
                    this.dispose();
                }
            }
            case "Liverpool" -> {
                if (rbEPL.isSelected()) {
                    result = ("""
                              Form 5 pertandingan Terakhir: W-W-W-D-D
                                                                       
                              Finish Pada Posisi ke-5 Di Liga
                              
                              = Kualifikasi UEFA Europa League 2023/2024 =
                              """);
                    labelW.setForeground(Color.black);
                    labelD.setForeground(Color.black);
                    labelL.setForeground(Color.black);
                } else if (rbFA.isSelected()) {
                    result = ("""
                              Third Round : D-W
                              (Rematch)
                              
                              Fourth Round : L
                              
                              = Gugur Pada Ronde Putaran ke-4  FA Cup =
                              """);
                    labelW.setForeground(Color.black);
                    labelD.setForeground(Color.black);
                    labelL.setForeground(Color.black);
                } else if (rbUCL.isSelected()) {
                    result = ("""
                              Group Stage : Lolos
                              Form : L-W-W-W-W-W
                              
                              Round of 16 : L-L
                              
                              = Gugur Pada Round Of 16 UEFA Champions Lague =
                              """);
                    labelW.setForeground(Color.black);
                    labelD.setForeground(Color.black);
                    labelL.setForeground(Color.black);
                } else {
                    Error1 warning = new Error1();
                    warning.setVisible(true);
                    this.dispose();
                }
            }
            case "Manchester City" -> {
                if (rbEPL.isSelected()) {
                    result = ("""
                              Form 5 pertandingan Terakhir: W-W-W-D-L
                                                                       
                              Finish Pada Posisi Pertama Di Liga
                              
                              = Kualifikasi UEFA Champions League 2023/2024 =
                              
                              = Kualifikasi Community Shield Cup =
                              
                              = JUARA PREMIER LEAGUE 2022/2023 =
                              """);
                    labelW.setForeground(Color.black);
                    labelD.setForeground(Color.black);
                    labelL.setForeground(Color.black);
                } else if (rbFA.isSelected()) {
                    result = ("""
                              Third Round : W
                              
                              Fourth Round : W
                              
                              Fifth Round : W
                              
                              Quarter Final : W
                              
                              Semi Final : W
                              
                              Final : W
                              
                              = JUARA FA CUP 2022/2023 =
                              """);
                    labelW.setForeground(Color.black);
                    labelD.setForeground(Color.black);
                    labelL.setForeground(Color.black);
                } else if (rbUCL.isSelected()) {
                    result = ("""
                              Group Stage : Lolos
                              Form : W-W-W-D-D-W
                              
                              Round of 16 : D-W
                              
                              Quarter Final : W-D
                              (Menang Agregate)
                              
                              Semi Final : D-W
                              (Menang Agregate)
                              
                              Final : -
                              
                              = Lolos Menuju Final UEFA Champions League 2022/2023=
                              """);
                    labelW.setForeground(Color.black);
                    labelD.setForeground(Color.black);
                    labelL.setForeground(Color.black);
                } else {
                    Error1 warning = new Error1();
                    warning.setVisible(true);
                    this.dispose();
                }
            }
            case "Manchester United" -> {
                if (rbEPL.isSelected()) {
                    result = ("""
                              Form 5 pertandingan Terakhir: L-W-W-W-W
                                                                       
                              Finish Pada Posisi ke-3 Di Liga
                              
                              = Kualifikasi UEFA Champions League 2023/2024 =
                              """);
                    labelW.setForeground(Color.black);
                    labelD.setForeground(Color.black);
                    labelL.setForeground(Color.black);
                } else if (rbFA.isSelected()) {
                    result = ("""
                              Third Round : W
                              
                              Fourth Round : W
                              
                              Fifth Round : W
                              
                              Quarter Final : W
                              
                              Semi Final : W
                              
                              Final : L
                              
                              = Kalah Pada Final FA Cup =
                              = Runner-Up FA Cup 2022/2023
                              """);
                    labelW.setForeground(Color.black);
                    labelD.setForeground(Color.black);
                    labelL.setForeground(Color.black);
                } else if (rbUEL.isSelected()) {
                    result = ("""
                              Group Stage : Lolos
                              Form : L-W-W-W-W-W
                              
                              Play-off : D-W
                              
                              Round of 16 : W-W
                              
                              Quarter Final : D-L
                              
                              = Gugur Pada Quarter Final UEFA Europa League =
                              """);
                    labelW.setForeground(Color.black);
                    labelD.setForeground(Color.black);
                    labelL.setForeground(Color.black);
                } else {
                    Error1 warning = new Error1();
                    warning.setVisible(true);
                    this.dispose();
                }
            }
        }
    ta.setText(result);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private javax.swing.JComboBox<String> cbClub;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelD;
    private javax.swing.JLabel labelL;
    private javax.swing.JLabel labelW;
    private javax.swing.JRadioButton rbEPL;
    private javax.swing.JRadioButton rbFA;
    private javax.swing.JRadioButton rbUCL;
    private javax.swing.JRadioButton rbUEL;
    private javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
}
